# Generated by Django 5.0.7 on 2024-08-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('employee_number', models.CharField(max_length=50)),
                ('ssid_token', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serverApp.permission')),
            ],
        ),
        migrations.CreateModel(
            name='JobCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serverApp.permissioncode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serverApp.user')),
            ],
        ),
    ]
