# Generated by Django 5.0.7 on 2024-08-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcode',
            name='permission_code',
        ),
        migrations.AddField(
            model_name='jobcode',
            name='permission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='serverApp.permission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='code',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PermissionCode',
        ),
    ]
