# Generated by Django 5.0.7 on 2024-08-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverApp', '0002_user_employee_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jobcode',
            name='permissionCode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='serverApp.permissioncode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissioncode',
            name='permission_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serverApp.permissiontype'),
        ),
    ]
