# Generated by Django 5.0.7 on 2024-08-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverApp', '0003_permissioncode_permissiontype_jobcode_permissioncode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcode',
            old_name='permissionCode',
            new_name='permission_code',
        ),
    ]
