# Generated by Django 5.0.7 on 2024-08-05 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverApp', '0004_rename_permissioncode_jobcode_permission_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='permissioncode',
            name='permission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='serverApp.permission'),
            preserve_default=False,
        ),
    ]
