# Generated by Django 5.0.7 on 2024-08-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverApp', '0005_permission_permissioncode_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ssid_token',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
