# Generated by Django 5.0.7 on 2024-08-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverApp', '0006_user_ssid_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
